version: '3.7'

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-vol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: oxid
      MYSQL_USER: root
      MYSQL_PASSWORD: oxid
      MYSQL_ROOT_PASSWORD: oxid
      TZ: Europe/Berlin
    networks:
      - internal

  mailhog:
    image: mailhog/mailhog:v1.0.0
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - internal

  php:
    build:
      context: build/php/
      args:
        HOST_USER_ID: ${HOST_USER_ID-0}
        HOST_GROUP_ID: ${HOST_GROUP_ID-0}
        HOST_USER_NAME: ${HOST_USER_NAME-root}
        HOST_GROUP_NAME: ${HOST_GROUP_NAME-root}
        MSMTP_CONFIG_APPEND: ${MSMTP_CONFIG_APPEND}
        WITH_XDEBUG: ${WITH_XDEBUG-1}
    restart: always
    environment:
      SHOP_SETUP_PATH: ${SHOP_SETUP_PATH}
      SHOP_TESTS_PATH: ${SHOP_TESTS_PATH}
      SHOP_URL: "http://oxideshop.local/"
      SELENIUM_SERVER_IP: "selenium"
    volumes:
      - type: bind
        source: ${PWD}/data/oxideshop
        target: /var/www/oxideshop
        consistency: consistent
        bind:
          propagation: shared
      - ${PWD}/build/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - db
      - mailhog
    networks:
      - internal

  webserver:
    image: httpd:2.4
    restart: always
    domainname: oxideshop.local
    hostname: oxideshop
    depends_on:
      - php
    volumes:
      - type: bind
        source: ${PWD}/data/oxideshop
        target: /var/www/oxideshop
        consistency: consistent
        bind:
          propagation: shared
      - ${PWD}/config/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - 80:80
    networks:
      internal:
        aliases:
          - localhost
          - oxideshop.local

  selenium:
    image: oxidesales/oxideshop-docker-selenium:S2FF31
    restart: always
    depends_on:
      - webserver
    ports:
      - 4444:4444
      - 5900:5900
    networks:
      - internal
    volumes:
      - type: bind
        source: ${PWD}/data/oxideshop
        target: /var/www/oxideshop
        consistency: consistent
        bind:
          propagation: shared
      - /dev/shm:/dev/shm

  sphinx:
    restart: "no"
    build:
      context: build/sphinx/
    volumes:
      - type: bind
        source: ${PWD}/data/dev-doc/
        target: /doc
        consistency: consistent
        bind:
          propagation: shared
    working_dir: /doc
    user: "${HOST_USER_ID-0}:${HOST_GROUP_ID-0}"

networks:
  internal:

volumes:
  db-vol:
