---
- name: Check for configuration file
  stat: "path={{ eshop.config.path }}"
  register: check_eshop_config

- name: Check for dist configuration file
  stat: "path={{ eshop.config.path_dist }}"
  register: check_eshop_config_dist

- name: Check for deploy configuration file
  stat: "path={{ eshop.config.path_deploy }}"
  register: check_eshop_config_deploy

- name: Copy dist configuration file
  shell: "cp {{ eshop.config.path_dist }} {{ eshop.config.path }}"
  when: not check_eshop_config.stat.exists and check_eshop_config_dist.stat.exists

- name: Copy deploy configuration file
  shell: "cp {{ eshop.config.path_deploy }} {{ eshop.config.path }}"
  when: not check_eshop_config.stat.exists and not check_eshop_config_dist.stat.exists and check_eshop_config_deploy.stat.exists

- name: Update configuration value
  shell: "sed -i 's|{{ item.pattern }}|{{ item.value }}|' {{ eshop.config.path }}"
  with_items:
    - {'pattern': '<dbHost.*>', 'value': "localhost"}
    - {'pattern': '<dbName.*>', 'value': "{{ mysql.database }}"}
    - {'pattern': '<dbUser.*>', 'value': "{{ mysql.user }}"}
    - {'pattern': '<dbPwd.*>', 'value': "{{ mysql.password }}"}
    - {'pattern': '<sShopURL.*>', 'value': "http://{{ apache.servername }}"}
    - {'pattern': '<sShopDir.*>', 'value': "{{ eshop_path.source }}"}
    - {'pattern': '<sCompileDir.*>', 'value': "{{ eshop_path.source }}/tmp"}
    - {'pattern': '<iUtfMode.*>', 'value': "{{ eshop.config.utf_mode }}"}

- name: Ensure temporary directory exists
  file: "path={{ eshop_path.source }}/tmp state=directory"

- name: Check if defined vendor directory exists
  stat: "path={{ eshop.composer.vendor }}"
  register: vendor_directory_exists

- name: Reset shop
  shell: "{{ eshop.composer.vendor }}/bin/reset-shop"
  ignore_errors: yes
  register: reset_shop
  when: vendor_directory_exists.stat.exists

- name: Reset shop if defined vendor directory does not exist
  shell: "{{ eshop_path.source }}/vendor/bin/reset-shop"
  ignore_errors: yes
  register: reset_shop_fallback
  when: not vendor_directory_exists.stat.exists

- name: Display warning about failed command line setup
  shell: 'true'
  notify: display reset shop error
  when: "(vendor_directory_exists.stat.exists and reset_shop.rc != 0) or (not vendor_directory_exists.stat.exists and reset_shop_fallback.rc != 0)"
