---
- name: Clean vendors
  file: "path={{ eshop.composer.root }}/vendor state=absent"
  when: eshop.composer.clean_vendors

- name: Download composer cache
  get_url: "url={{ eshop.composer.cache_url }} dest=/tmp/composer_cache.tar.gz"
  when: eshop.composer.cache_url

- name: Extract composer cache
  unarchive: src=/tmp/composer_cache.tar.gz dest=~/.composer/ copy=no
  when: eshop.composer.cache_url

- name: Create composer json file
  get_url:
    url: "{{ eshop.composer.json_source_url }}"
    dest: "{{ eshop.composer.root }}/composer.json"
  register: create_composer_json

- name: Create composer lock file
  get_url:
    url: "{{ eshop.composer.lock_source_url }}"
    dest: "{{ eshop.composer.root }}/composer.lock"
  when: create_composer_json.changed

- name: Run composer install
  shell: "cd {{ eshop.composer.root }} && {{ eshop.composer.env }} composer install --prefer-{{ eshop.composer.prefer }}"
