---
- name: Clone out module certification tools
  git: "repo={{ eshop.sdk.module_certification_tools.repo }} dest={{ eshop.sdk.path }}/module_certification_tools"
  tags:
    - eshop
    - eshop_sdk

- name: Run composer install
  shell: cd {{ eshop.sdk.path }}/module_certification_tools/ && composer install
  tags:
    - eshop
    - eshop_sdk

- name: Place module certification tools shortcut
  template: src=ox_cert dest={{ eshop.sdk.path }}/bin/ox_cert mode=0755
  tags:
    - eshop
    - eshop_sdk

- name: Add information about module certification tools shortcut
  shell: "echo 'ox_cert - Module certification tools' >> {{ eshop_sdk_info_file }}"
  tags:
    - eshop
    - eshop_sdk
