---
vagrant_local:
  vm:
    name: oxideshop
    hostname: oxideshop.dev
    aliases:
      - www.oxideshop.dev
      - localhost
    app_shared_folder:
      source: oxideshop
      target: /var/www/oxideshop
server:
  packages:
    - git
apache:
  docroot: "{{ eshop_path.source }}"
  servername: "{{ eshop.fqdn }}"
mysql:
  root_password: oxid
  database: oxid
  user: oxid
  password: oxid
php:
  zendguard:
    install: false
  packages:
    - php5-cli
    - php5-intl
    - php5-mcrypt
    - php5-mysql
    - php5-gd
    - php5-curl
  composer:
    prestissimo:
      install: true
mailhog:
  install: true
adminer:
  install: true
adminer_editor:
  install: true
varnish:
  default_config:
    source: "{{ eshop_path.library }}/ReverseProxy/Varnish/default.vcl"
    target: /etc/varnish/default.vcl
  servers_config:
    source: "{{ eshop_path.library }}/ReverseProxy/Varnish/servers_conf.vcl.varnish_4.dist"
    target: /etc/varnish/servers_conf.vcl
selenium:
  install: false
  package:
    firefox:
      deb_url: http://downloads.sourceforge.net/project/ubuntuzilla/mozilla/apt/pool/main/f/firefox-mozilla-build/firefox-mozilla-build_31.0-0ubuntu1_amd64.deb
    self:
      jar_url: http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar
