---
eshop_target_path: "{{ vagrant_local.vm.app_shared_folder.target }}"
eshop_path:
    root: "{{ eshop_target_path }}"
    source: "{{ eshop_target_path }}/source"
    tests: "{{ eshop_target_path }}/tests"
    library: "{{ eshop_target_path }}/library"
    modules: "{{ eshop_target_path }}/source/modules"
    composer: "{{ eshop_target_path }}/source"
eshop:
  fqdn: "{{ vagrant_local.vm.aliases.0 }}"
  config:
    utf_mode: 0
  composer:
    clean_vendors: true
    env: "SHOP_PATH=\"'{{ eshop_path.source }}'\" SHOP_TESTS_PATH='{{ eshop_path.tests }}' PARTIAL_MODULE_PATHS='null'"
    root: "{{ eshop_path.composer }}"
    vendor: "{{ eshop_path.composer }}/vendor"
    cache_url: ~
    json_source_url: https://raw.githubusercontent.com/OXID-eSales/oxideshop_ce/b-5.2-ce/source/composer.json
    lock_source_url: https://raw.githubusercontent.com/OXID-eSales/oxideshop_ce/b-5.2-ce/source/composer.lock
    prefer: dist
  source:
    repo: https://github.com/OXID-eSales/oxideshop_ce.git
    version: b-5.3-ce
  sdk:
    path: ~/eshop_sdk
    module_skeleton_generator:
      install: true
      repo: https://github.com/OXID-eSales/module_skeleton_generator.git
    module_certification_tools:
      install: true
      repo: https://github.com/OXID-eSales/module_certification_tools.git
