---
vagrant_local:
  vm:
    name: oxideshop
    hostname: oxideshop.local
    aliases:
      - www.oxideshop.local
    app_shared_folder:
      source: oxideshop
      target: /var/www/oxideshop
server:
  packages:
    - git
landing:
  install: false
apache:
  docroot: "{{ eshop_path.source }}"
  servername: "{{ vagrant_local.vm.hostname }}"
mysql:
  root_password: oxid
  database: oxid
  user: oxid
  password: oxid
php:
  zendguard:
    install: false
  packages:
    - php5.6-cli
    - php5.6-intl
    - php5.6-mcrypt
    - php5.6-mysql
    - php5.6-gd
    - php5.6-curl
    - php5.6-xml
    - php5.6-bcmath
    - php5.6-mbstring
    - php5.6-soap
  composer:
    prestissimo:
      install: true
mailhog:
  install: true
adminer:
  install: true
adminer_editor:
  install: true
eshop_path:
  root: "{{ vagrant_local.vm.app_shared_folder.target }}"
  source: "{{ vagrant_local.vm.app_shared_folder.target }}/source"

